pipeline:
  test:
    image: debian:bookworm-slim
    commands:
      # Install system dependencies
      - apt-get update
      - apt-get install -y curl gnupg lsb-release libwolfssl-dev libnghttp2-dev build-essential
      
      # Add Zig repository and install
      - curl -sS https://debian.griffo.io/EA0F721D231FDD3A0A17B9AC7808B4DD62C41256.asc | gpg --dearmor --yes -o /etc/apt/trusted.gpg.d/debian.griffo.io.gpg
      - echo "deb https://debian.griffo.io/apt bookworm main" > /etc/apt/sources.list.d/debian.griffo.io.list
      - apt-get update
      - apt-get install -y zig
      
      # Build and test
      - zig build test