variables:
  - &ZIG_VERSION "0.14.0"
  - &BASE_IMAGE "ubuntu:24.04"

when:
  event: [push, pull_request]

matrix:
  platform:
    - linux/amd64
    - linux/arm64

steps:
  test:
    image: *BASE_IMAGE
    environment:
      ZIG_VERSION: *ZIG_VERSION
    commands:
      - apt-get update
      - apt-get install -y curl wget xz-utils libwolfssl-dev libnghttp2-dev build-essential
      - wget https://ziglang.org/download/$${ZIG_VERSION}/zig-linux-x86_64-$${ZIG_VERSION}.tar.xz
      - tar -xf zig-linux-x86_64-$${ZIG_VERSION}.tar.xz
      - mv zig-linux-x86_64-$${ZIG_VERSION} /opt/zig
      - ln -s /opt/zig/zig /usr/local/bin/zig
      - zig build test

---

when:
  event: push
  branch: main

matrix:
  platform:
    - linux/amd64
    - linux/arm64

steps:
  test-after-merge:
    image: *BASE_IMAGE
    environment:
      ZIG_VERSION: *ZIG_VERSION
    commands:
      - apt-get update
      - apt-get install -y curl wget xz-utils libwolfssl-dev libnghttp2-dev build-essential
      - wget https://ziglang.org/download/$${ZIG_VERSION}/zig-linux-x86_64-$${ZIG_VERSION}.tar.xz
      - tar -xf zig-linux-x86_64-$${ZIG_VERSION}.tar.xz
      - mv zig-linux-x86_64-$${ZIG_VERSION} /opt/zig
      - ln -s /opt/zig/zig /usr/local/bin/zig
      - zig build test
